### ISSUE TITLE
Separate data into a fixture

### ISSUE THREAD

**Issue by alessandrofelder** [UCL-RITS/rse-classwork-2020#92]
## Separating data from code

Your parametrised bit now probably got a bit too big and difficult to read.
Create a `fixture.yaml` file where you can store what you parametrised before
in a more human readable way.

Load the yaml file within the test and use it that structure to feed the parametrize test.

The `fixture.yaml` could look like:
```yaml
- generic:
    time_range_1: ...
    time_range_2: ...
    expected: 
        - ...
        - ...
- no_overlap:
    time_range_1: ...
    time_range_2: ...
    expected: []
```

A sample solution to this exercise can be seen [here](https://gist.github.com/alessandrofelder/f3d431964c9cf1a6d4d9c06f821214a9).
